"""init

Revision ID: 334fe8266ec4
Revises: 
Create Date: 2026-05-07 20:11:20.551488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334fe8266ec4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index('ix_customers_cnpj', 'customers', ['cnpj'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('items_per_box', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean')
    )
    op.create_index('ix_products_ean', 'products', ['ean'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CHECKED_OUT', name='cart_status'), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_carts_customer_id', 'carts', ['customer_id'], unique=False)
    op.create_index('ix_carts_status', 'carts', ['status'], unique=False)
    op.create_index('ux_carts_open_per_customer', 'carts', ['customer_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('validity', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offers_customer_id', 'offers', ['customer_id'], unique=False)
    op.create_index('ix_offers_product_id', 'offers', ['product_id'], unique=False)
    op.create_index('ix_offers_validity', 'offers', ['validity'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'offer_id', name='ux_cart_items_cart_offer')
    )
    op.create_index('ix_cart_items_cart_id', 'cart_items', ['cart_id'], unique=False)
    op.create_index('ix_cart_items_offer_id', 'cart_items', ['offer_id'], unique=False)
    op.create_table('checkouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAID', name='checkout_status'), nullable=False),
    sa.Column('payment_method', sa.Enum('PIX', name='payment_method'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', name='ux_checkouts_cart')
    )
    op.create_index('ix_checkouts_cart_id', 'checkouts', ['cart_id'], unique=False)
    op.create_index('ix_checkouts_customer_id', 'checkouts', ['customer_id'], unique=False)
    op.create_index('ix_checkouts_status', 'checkouts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_checkouts_status', table_name='checkouts')
    op.drop_index('ix_checkouts_customer_id', table_name='checkouts')
    op.drop_index('ix_checkouts_cart_id', table_name='checkouts')
    op.drop_table('checkouts')
    op.drop_index('ix_cart_items_offer_id', table_name='cart_items')
    op.drop_index('ix_cart_items_cart_id', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index('ix_offers_validity', table_name='offers')
    op.drop_index('ix_offers_product_id', table_name='offers')
    op.drop_index('ix_offers_customer_id', table_name='offers')
    op.drop_table('offers')
    op.drop_index('ux_carts_open_per_customer', table_name='carts', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index('ix_carts_status', table_name='carts')
    op.drop_index('ix_carts_customer_id', table_name='carts')
    op.drop_table('carts')
    op.drop_index('ix_products_ean', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_customers_cnpj', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
